### PR TITLE
Node embedding

### PR DESCRIPTION
**Pull request by alanyuchenhou**
This pull request has the main file node_embedding.tex for the conference paper submission. The code review feature of Github should let you to leave comments on the website directly (it's under the "files changed" tab of this pull request page). Hope to get feedback from you soon! It should also let you commit changes to the code as I added you in this repo as a collaborator.

### CODE REVIEW

**Comment by alanyuchenhou** [comment]
Attach PDF
[node_embedding.pdf](https://github.com/yuchenhou/cave/files/182770/node_embedding.pdf)
.

**Comment by alanyuchenhou** [comment]
This is the new PDF:
[node_embedding.pdf](https://github.com/yuchenhou/cave/files/201912/node_embedding.pdf)

Can you use only the yellow comments and the red deletion marks? I can see the addition/replacement marks but I can't see the contents in them.

**Comment by ghost** [comment]
I will try to put the addition marks into a yellow comment.

I would also like for you to find a way to indicate where you've made changes (so I don't have to hunt for them or re-read the entire paper each time). If you want to use Latex, then there are macros for this kind of thing (mostly using colors to indicate new/deleted/modified text). Or you can just highlight the areas where changes occurred.

**Comment by alanyuchenhou** [comment]
I think what you want is some diff utility. I know github shows the diff between any 2 versions in the commits tab (or files changed tab): https://github.com/yuchenhou/cave/pull/1/commits/50fb8beec93feb30628e279c682f0a91bedaf62b

But that's for the code only, not the pdf. For pdf, I found acrobat can diff 2 pdfs: https://helpx.adobe.com/acrobat/using/compare-documents.html
Can you use this feature of acrobat?

**Comment by ghost** [comment]
I will try. But you really need to think about upgrading your approach to writing/editing papers. I know students like free software, but MSWord and Adobe Acrobat's reviewing functionality is way beyond the Latex/diff approach. And it's free for students. Even OpenOffice and GoogleDocs are a step up (and they're completely free).

**Comment by alanyuchenhou** [comment]
OK. It'll be nice to upgrade my tools and workflow. On other issue, I just fixed some problems I introduced into the paper yesterday when I added more experiments. Here is the updated PDF:
[node_embedding.pdf](https://github.com/yuchenhou/cave/files/203227/node_embedding.pdf)

**Comment by alanyuchenhou** [comment]
This is the new PDF:
[node_embedding.pdf](https://github.com/yuchenhou/cave/files/226908/node_embedding.pdf)

**Comment by alanyuchenhou** [comment]
I clarified the branding a bit and refactored the abstract following this [guide](http://www.nature.com/nature/authors/gta/2c_Summary_para.pdf). This is the new version:
[node_embedding.pdf](https://github.com/yuchenhou/cave/files/229480/node_embedding.pdf)

**Comment by alanyuchenhou** [comment]
The previous revision introduced some inconsistencies in the paper. I just revised it again from begin to end to fix them: 

[node_embedding.pdf](https://github.com/yuchenhou/cave/files/233149/node_embedding.pdf)

**Comment by alanyuchenhou** [comment]
A new version is ready for you to review:
[node_embedding.pdf](https://github.com/yuchenhou/cave/files/240018/node_embedding.pdf)

**Pull request merged**
